version: '3.8'

services:
  postgres-db-payment:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fiap-lanches-payment
    ports:
      - "5435:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    networks:
      - fiap-lanchonet-network
        
  fiap-lanches-payment-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - fiap-lancher:/var/lib/fiaplancher/data
    depends_on:
      - postgres-db-payment
    networks:
      - fiap-lanchonet-network

networks:
  fiap-lanchonet-network:
    external: true

volumes:
  postgres-db:
    driver: local
  fiap-lancher:
    driver: local
